PREFIX owl: <http://www.w3.org/2002/07/owl#>

INSERT {?O ?Q ?S} WHERE  {?P owl:inverseOf ?Q. ?S ?P ?O}
INSERT {?O ?P ?S} WHERE  {?P owl:inverseOf ?Q. ?S ?Q ?O} 
INSERT {?Q owl:inverseOf ?P} WHERE  {?P owl:inverseOf ?Q} 
