PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX elodzh: <https://github.com/stazh/sw-ehedaten/tree/main/ontology/elodzh#>

SELECT ?year ?weekdayLabel WHERE{
?me elodzh:marriageEntryDocumentsWeddingWithCertaintyValue elodzh:Likely.
?me elodzh:marriageEntryHasDatingOnDate ?date.
BIND(year(?date) AS ?year)
?me elodzh:marriageEntryHasDatingOnWeekday ?weekday.
?weekday rdfs:label ?weekdayLabel.
filter(lang(?weekdayLabel) = 'de')
?me elodzh:marriageEntryIsInParishBook ?pb.
?pb elodzh:parishBookIsKeptByParish ?kirchgemeinde.
?kirchgemeinde elodzh:parishHasSeatAtPlace ?ort.
filter(?ort = 'Zürich' || ?ort = 'Winterthur')
}
